Feature: Interactive Mode
rakuri255/UltraSinger pull request #198
Opened 2024-12-20 00:45 UTC by agwosdz

Added command line argument --interactive to use interactive mode for parameter selection to make it more user friendly for novice users :)

![image](https://github.com/user-attachments/assets/bb84688e-e39f-4fea-8dd8-8ce85cb72070)

It also allows for Smashing Enter to keep everything default

Also, made the stars printed in print_version dynamic :)

2024-12-21 21:05 UTC, rakuri255 requested changes

2024-12-21 21:05 UTC, rakuri255 commented on src/Settings.py
> +    interactive_mode = False
Add it also to the Readme as section

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    settings.interactive_mode = False
Its already `False` from the settings

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +def init_settings_interactive() -> Settings:
Maybe to own file? InteractivSettings.py ?

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Input file
This function is too big. We could use your headers as functions.
CodeFactory also see it as an issue. Have you access to them?

def __ask_input_file()

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Output folder
def __ask_output_folder()

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Whisper model
def __ask_whisper_model()

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Display options in 4 columns using Table
def __add_colums(i: short)

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Whisper align model
def __ask_whisper_align_model

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # DEMUCS model
def __ask_demucs_model

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Display options in 4 columns using Table
duplicate

2024-12-21 21:05 UTC, rakuri255 commented on src/UltraSinger.py
> +    # Additional options
def __ask_additional_options()

I think we dont need extra functions for all these additional stuff :)

2024-12-21 21:06 UTC, rakuri255 commented
I like this interavtive mode!

2024-12-22 15:57 UTC, agwosdz commented on src/Settings.py
> +    interactive_mode = False
removed

2024-12-22 15:57 UTC, agwosdz commented on src/UltraSinger.py
> +def init_settings_interactive() -> Settings:
Moved to module/init_interactive_mode.py

2024-12-22 15:58 UTC, agwosdz commented on src/UltraSinger.py
> +    settings.interactive_mode = False
removed

2024-12-22 15:58 UTC, agwosdz commented on src/UltraSinger.py
> +    # Input file
I saw that, moved to own module, and split up into separate functions

2024-12-22 16:00 UTC, agwosdz commented on src/UltraSinger.py
> +    # Output folder
moved to get_output_folder in init_interactive_mode.py

2024-12-22 16:01 UTC, agwosdz commented on src/UltraSinger.py
> +    # Whisper align model
combined to one function select_model in init_interactive_mode.py

2024-12-22 16:04 UTC, agwosdz commented on src/UltraSinger.py
> +    # Display options in 4 columns using Table
With the rewrite, I don't think that is needed anymore

2024-12-22 16:05 UTC, agwosdz commented on src/UltraSinger.py
> +    # Whisper model
combined into select_model in init_interactive_mode.py

2024-12-22 16:05 UTC, agwosdz commented on src/UltraSinger.py
> +    # Additional options
Agreed, all additional options are handled by one function.
configure_additional_options in init_interactive_mode.py

2024-12-22 16:06 UTC, agwosdz commented on src/UltraSinger.py
> +    # Display options in 4 columns using Table
resolved with rewrite

2024-12-22 16:06 UTC, agwosdz commented on src/UltraSinger.py
> +    # DEMUCS model
solved in combined select_model function in init_interactive_mode.py

2024-12-25 00:32 UTC, rakuri255 approved these changes

2024-12-25 14:45 UTC, rakuri255 commented
@agwosdz can you upmerge it? Than i reintegrste it 😀

2024-12-25 23:26 UTC, merged